// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";

bytes32 constant _tableId = bytes32(abi.encodePacked(bytes16(""), bytes16("SFOpenStreamTabl")));
bytes32 constant SFOpenStreamTableTableId = _tableId;

library SFOpenStreamTable {
  /** Get the table's schema */
  function getSchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](1);
    _schema[0] = SchemaType.INT96;

    return SchemaLib.encode(_schema);
  }

  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](2);
    _schema[0] = SchemaType.ADDRESS;
    _schema[1] = SchemaType.ADDRESS;

    return SchemaLib.encode(_schema);
  }

  /** Get the table's metadata */
  function getMetadata() internal pure returns (string memory, string[] memory) {
    string[] memory _fieldNames = new string[](1);
    _fieldNames[0] = "flowRate";
    return ("SFOpenStreamTable", _fieldNames);
  }

  /** Register the table's schema */
  function registerSchema() internal {
    StoreSwitch.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Register the table's schema (using the specified store) */
  function registerSchema(IStore _store) internal {
    _store.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Set the table's metadata */
  function setMetadata() internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    StoreSwitch.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Set the table's metadata (using the specified store) */
  function setMetadata(IStore _store) internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    _store.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Get flowRate */
  function get(address token, address receiver) internal view returns (int96 flowRate) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160((token))));
    _keyTuple[1] = bytes32(uint256(uint160((receiver))));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 0);
    return (int96(uint96(Bytes.slice12(_blob, 0))));
  }

  /** Get flowRate (using the specified store) */
  function get(IStore _store, address token, address receiver) internal view returns (int96 flowRate) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160((token))));
    _keyTuple[1] = bytes32(uint256(uint160((receiver))));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 0);
    return (int96(uint96(Bytes.slice12(_blob, 0))));
  }

  /** Set flowRate */
  function set(address token, address receiver, int96 flowRate) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160((token))));
    _keyTuple[1] = bytes32(uint256(uint160((receiver))));

    StoreSwitch.setField(_tableId, _keyTuple, 0, abi.encodePacked((flowRate)));
  }

  /** Set flowRate (using the specified store) */
  function set(IStore _store, address token, address receiver, int96 flowRate) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160((token))));
    _keyTuple[1] = bytes32(uint256(uint160((receiver))));

    _store.setField(_tableId, _keyTuple, 0, abi.encodePacked((flowRate)));
  }

  /** Tightly pack full data using this table's schema */
  function encode(int96 flowRate) internal view returns (bytes memory) {
    return abi.encodePacked(flowRate);
  }

  /** Encode keys as a bytes32 array using this table's schema */
  function encodeKeyTuple(address token, address receiver) internal pure returns (bytes32[] memory _keyTuple) {
    _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160((token))));
    _keyTuple[1] = bytes32(uint256(uint160((receiver))));
  }

  /* Delete all data for given keys */
  function deleteRecord(address token, address receiver) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160((token))));
    _keyTuple[1] = bytes32(uint256(uint160((receiver))));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /* Delete all data for given keys (using the specified store) */
  function deleteRecord(IStore _store, address token, address receiver) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(uint160((token))));
    _keyTuple[1] = bytes32(uint256(uint160((receiver))));

    _store.deleteRecord(_tableId, _keyTuple);
  }
}
