// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";

bytes32 constant _tableId = bytes32(abi.encodePacked(bytes16(""), bytes16("SFStoreTable")));
bytes32 constant SFStoreTableTableId = _tableId;

struct SFStoreTableData {
  address storeAddress;
  address inResource;
  address outResource;
  int96 maxFlowRate;
}

library SFStoreTable {
  /** Get the table's schema */
  function getSchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](4);
    _schema[0] = SchemaType.ADDRESS;
    _schema[1] = SchemaType.ADDRESS;
    _schema[2] = SchemaType.ADDRESS;
    _schema[3] = SchemaType.INT96;

    return SchemaLib.encode(_schema);
  }

  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](1);
    _schema[0] = SchemaType.UINT32;

    return SchemaLib.encode(_schema);
  }

  /** Get the table's metadata */
  function getMetadata() internal pure returns (string memory, string[] memory) {
    string[] memory _fieldNames = new string[](4);
    _fieldNames[0] = "storeAddress";
    _fieldNames[1] = "inResource";
    _fieldNames[2] = "outResource";
    _fieldNames[3] = "maxFlowRate";
    return ("SFStoreTable", _fieldNames);
  }

  /** Register the table's schema */
  function registerSchema() internal {
    StoreSwitch.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Register the table's schema (using the specified store) */
  function registerSchema(IStore _store) internal {
    _store.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Set the table's metadata */
  function setMetadata() internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    StoreSwitch.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Set the table's metadata (using the specified store) */
  function setMetadata(IStore _store) internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    _store.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Get storeAddress */
  function getStoreAddress(uint32 id) internal view returns (address storeAddress) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256((id)));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 0);
    return (address(Bytes.slice20(_blob, 0)));
  }

  /** Get storeAddress (using the specified store) */
  function getStoreAddress(IStore _store, uint32 id) internal view returns (address storeAddress) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256((id)));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 0);
    return (address(Bytes.slice20(_blob, 0)));
  }

  /** Set storeAddress */
  function setStoreAddress(uint32 id, address storeAddress) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256((id)));

    StoreSwitch.setField(_tableId, _keyTuple, 0, abi.encodePacked((storeAddress)));
  }

  /** Set storeAddress (using the specified store) */
  function setStoreAddress(IStore _store, uint32 id, address storeAddress) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256((id)));

    _store.setField(_tableId, _keyTuple, 0, abi.encodePacked((storeAddress)));
  }

  /** Get inResource */
  function getInResource(uint32 id) internal view returns (address inResource) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256((id)));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 1);
    return (address(Bytes.slice20(_blob, 0)));
  }

  /** Get inResource (using the specified store) */
  function getInResource(IStore _store, uint32 id) internal view returns (address inResource) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256((id)));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 1);
    return (address(Bytes.slice20(_blob, 0)));
  }

  /** Set inResource */
  function setInResource(uint32 id, address inResource) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256((id)));

    StoreSwitch.setField(_tableId, _keyTuple, 1, abi.encodePacked((inResource)));
  }

  /** Set inResource (using the specified store) */
  function setInResource(IStore _store, uint32 id, address inResource) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256((id)));

    _store.setField(_tableId, _keyTuple, 1, abi.encodePacked((inResource)));
  }

  /** Get outResource */
  function getOutResource(uint32 id) internal view returns (address outResource) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256((id)));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 2);
    return (address(Bytes.slice20(_blob, 0)));
  }

  /** Get outResource (using the specified store) */
  function getOutResource(IStore _store, uint32 id) internal view returns (address outResource) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256((id)));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 2);
    return (address(Bytes.slice20(_blob, 0)));
  }

  /** Set outResource */
  function setOutResource(uint32 id, address outResource) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256((id)));

    StoreSwitch.setField(_tableId, _keyTuple, 2, abi.encodePacked((outResource)));
  }

  /** Set outResource (using the specified store) */
  function setOutResource(IStore _store, uint32 id, address outResource) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256((id)));

    _store.setField(_tableId, _keyTuple, 2, abi.encodePacked((outResource)));
  }

  /** Get maxFlowRate */
  function getMaxFlowRate(uint32 id) internal view returns (int96 maxFlowRate) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256((id)));

    bytes memory _blob = StoreSwitch.getField(_tableId, _keyTuple, 3);
    return (int96(uint96(Bytes.slice12(_blob, 0))));
  }

  /** Get maxFlowRate (using the specified store) */
  function getMaxFlowRate(IStore _store, uint32 id) internal view returns (int96 maxFlowRate) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256((id)));

    bytes memory _blob = _store.getField(_tableId, _keyTuple, 3);
    return (int96(uint96(Bytes.slice12(_blob, 0))));
  }

  /** Set maxFlowRate */
  function setMaxFlowRate(uint32 id, int96 maxFlowRate) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256((id)));

    StoreSwitch.setField(_tableId, _keyTuple, 3, abi.encodePacked((maxFlowRate)));
  }

  /** Set maxFlowRate (using the specified store) */
  function setMaxFlowRate(IStore _store, uint32 id, int96 maxFlowRate) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256((id)));

    _store.setField(_tableId, _keyTuple, 3, abi.encodePacked((maxFlowRate)));
  }

  /** Get the full data */
  function get(uint32 id) internal view returns (SFStoreTableData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256((id)));

    bytes memory _blob = StoreSwitch.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Get the full data (using the specified store) */
  function get(IStore _store, uint32 id) internal view returns (SFStoreTableData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256((id)));

    bytes memory _blob = _store.getRecord(_tableId, _keyTuple, getSchema());
    return decode(_blob);
  }

  /** Set the full data using individual values */
  function set(uint32 id, address storeAddress, address inResource, address outResource, int96 maxFlowRate) internal {
    bytes memory _data = encode(storeAddress, inResource, outResource, maxFlowRate);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256((id)));

    StoreSwitch.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using individual values (using the specified store) */
  function set(
    IStore _store,
    uint32 id,
    address storeAddress,
    address inResource,
    address outResource,
    int96 maxFlowRate
  ) internal {
    bytes memory _data = encode(storeAddress, inResource, outResource, maxFlowRate);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256((id)));

    _store.setRecord(_tableId, _keyTuple, _data);
  }

  /** Set the full data using the data struct */
  function set(uint32 id, SFStoreTableData memory _table) internal {
    set(id, _table.storeAddress, _table.inResource, _table.outResource, _table.maxFlowRate);
  }

  /** Set the full data using the data struct (using the specified store) */
  function set(IStore _store, uint32 id, SFStoreTableData memory _table) internal {
    set(_store, id, _table.storeAddress, _table.inResource, _table.outResource, _table.maxFlowRate);
  }

  /** Decode the tightly packed blob using this table's schema */
  function decode(bytes memory _blob) internal pure returns (SFStoreTableData memory _table) {
    _table.storeAddress = (address(Bytes.slice20(_blob, 0)));

    _table.inResource = (address(Bytes.slice20(_blob, 20)));

    _table.outResource = (address(Bytes.slice20(_blob, 40)));

    _table.maxFlowRate = (int96(uint96(Bytes.slice12(_blob, 60))));
  }

  /** Tightly pack full data using this table's schema */
  function encode(
    address storeAddress,
    address inResource,
    address outResource,
    int96 maxFlowRate
  ) internal view returns (bytes memory) {
    return abi.encodePacked(storeAddress, inResource, outResource, maxFlowRate);
  }

  /** Encode keys as a bytes32 array using this table's schema */
  function encodeKeyTuple(uint32 id) internal pure returns (bytes32[] memory _keyTuple) {
    _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256((id)));
  }

  /* Delete all data for given keys */
  function deleteRecord(uint32 id) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256((id)));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /* Delete all data for given keys (using the specified store) */
  function deleteRecord(IStore _store, uint32 id) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256((id)));

    _store.deleteRecord(_tableId, _keyTuple);
  }
}
