// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Counter, CounterTableId } from "./tables/Counter.sol";
import { SFContractTable, SFContractTableTableId } from "./tables/SFContractTable.sol";
import { SFSuperTokenTable, SFSuperTokenTableTableId } from "./tables/SFSuperTokenTable.sol";
import { SFResourceGeneratorTable, SFResourceGeneratorTableTableId } from "./tables/SFResourceGeneratorTable.sol";
import { SFStoreTable, SFStoreTableData, SFStoreTableTableId } from "./tables/SFStoreTable.sol";
import { SFOpenStreamTable, SFOpenStreamTableTableId } from "./tables/SFOpenStreamTable.sol";
import { Position, PositionData, PositionTableId } from "./tables/Position.sol";
