// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ISapphireSystem {
  function setSapphireStream() external returns (bool);

  function deleteSapphireStream(address receiver) external returns (bool);
}
